struct doc_status {
	char insec;
	char insubsec;
	char inmetatex;
	mawxml* m;
};

static void begin_document(void* data);
static void end_document(void* data);
static void meta_kv(void* data, char* key, char* value);
static void meta_tex(void* data, char* line);
static void meta_end(void* data);
static void begin_tex(void* data);
static void begin_tex_math(void* data);
static void begin_tex_html(void* data);
static void texchar(void* data, char cc);
static void end_tex(void* data);
static void end_tex_math(void* data);
static void end_tex_html(void* data);
static void section(void* data, char* title);
static void close_subsec(struct doc_status* d);
static void subsection(void* data, char* title);
static void cdata2(void* data, char* cdata);
static void paragraph(void* data);
static void forced_space(void* data);
static void link(void* data, char* title, char* dest);
static void begin_emphasis(void* data);
static void end_emphasis(void* data);
static void begin_english_quot(void* data);
static void begin_quot(struct doc_status* s, char* lang);
static void end_quot(void* data);
static void begin_german_quot(void* data);
#define DSYMF(F) static void sym_##F(void* data)
DSYMF(rightarrow1);
DSYMF(rightarrow2);
DSYMF(leftarrow);
DSYMF(dots);
DSYMF(smiley);
DSYMF(math_in);
DSYMF(dash);
DSYMF(half_space);
DSYMF(exclamation);
#undef DSYMF
static void symbol(void* data, char* name, unsigned entity);
static void process_exp(void* data, char* a, char* b);
static void begin_shortcut(void* data);
static void shortcut_key(void* data, char* key);
static void end_shortcut(void* data);
static void begin_code_inline(void* data);
static void end_code_inline(void* data);
static void begin_table(void* data, char* caption);
static void begin_table_field(void* data);
static void end_table_field(void* data);
static void table_newline(void* data);
static void table_mid_sep(void* data);
static void end_table(void* data);
static void begin_list_group(void* data);
static void begin_list(void* data, char lc);
static void begin_list_description_title(void* data);
static void end_list_description_title(void* data);
static void begin_list_item(void* data);
static void end_list_item(void* data);
static void end_list(void* data);
static void end_list_group(void* data);
static void begin_code(void* data);
static void end_code(void* data);
